### ISSUE TITLE
Output time format is incorrect

### ISSUE THREAD

**Issue by tilgovi** [remix/partridge#52]
* partridge version: v1.0.0
* Python version: v3.7.1
* Operating System: macOS

### Description

Writing a feed outputs time columns in seconds since midnight. They should be formatted as 'HH:MM:SS'.

**Comment by invisiblefunnel** [comment]
When calling `write_feed_dangerously`, you have to make sure that the result of calling `.to_csv(path, index=False)` on all of the DataFrames is valid GTFS. By default, Partridge converts `HH:MM:SS` to seconds-since-midnight, so the values will be written to the CSV in seconds instead of a `HH:MM:SS`-formatted string.

It's possible to use `write_feed_dangerously` with `load_raw_feed` if you also ensure that any changes to the data work as expected with `.to_csv`. @csb19815 does this often in his scripts.

I've tried to discourage using `write_feed_dangerously` directly in a few ways, including the scary name. Let me know if anyone has ideas for making this less confusing though. This is still a rough edge in Partridge.
