### ISSUE TITLE
Float representation of the parsed time is currently incorrect

### ISSUE THREAD

**Issue by invisiblefunnel** [remix/partridge#54]
Related (or maybe the same issue) is that GTFS specifies that times are seconds since noon minus 12 hours. For calendar days when there is a daylight savings shift, the float representation of the parsed time is currently incorrect.

_Originally posted by @tilgovi in https://github.com/remix/partridge/issues/42#issuecomment-452141549_

**Comment by tilgovi** [comment]
Since the float representation is only created when reading the feed for transformation purposes, and Partridge does not expose an interfacing for writing the feed back out, it's sufficient to say that these floats are "seconds since noon minus 12h", just as the GTFS specification does with its time representations.

**Comment by invisiblefunnel** [comment]
cc @genhernandez
